### ISSUE TITLE
[BUG] Object data not loaded with condition

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#152]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4.5
* Laravel version: 7.0
* Laraform Vue package version and type: 1.2.8 PRO
* Laraform Laravel package version: 1.2.2

### Description

When loading data to the form inside a object the data is not loaded when using a condition. Without the condition the data is loaded correctly.

### Steps to Reproduce

Controller
```
$scorecard['course_country_code'] = 'BE';
$scorecard['foreign_course_details'] = [
    'course'     => 'blabla',
    'loop_name'  => 'blabla',
    'tee_name'   => 'blabla',
    'courserate' => 'blabla',
    'sloperate'  => 'blabla',
    'total_par'  => 'blabla',
    'stableford' => 'blabla',
];

$form = $this->form()->load($scorecard);
```

Form
```
public function schema()
{
return [
    'course_country_code'    => [
        'type'   => 'select',
        'label'  => 'Land',
        'items'  => $this->countries(),
        'search' => true,
        'rules'  => ['required']
    ],
    'foreign_course_details' => [
        'type'   => 'object',
        'label'  => 'Buitenlandse baan',
        'schema' => [
            'course'     => [
                'type'  => 'text',
                'label' => 'Baan',
                'rules' => ['required']
            ],
            'loop_name'  => [
                'type'    => 'text',
                'label'   => 'Lus',
                'rules'   => ['required'],
                'columns' => 6
            ],
            'tee_name'   => [
                'type'    => 'text',
                'label'   => 'Afslagpunt',
                'rules'   => ['required'],
                'columns' => 6
            ],
            'courserate' => [
                'type'    => 'text',
                'label'   => 'Baanrating',
                'rules'   => ['required'],
                'columns' => 3
            ],
            'sloperate'  => [
                'type'      => 'text',
                'inputType' => 'number',
                'label'     => 'Sloperate',
                'rules'     => ['required'],
                'columns'   => 3
            ],
            'total_par'  => [
                'type'      => 'text',
                'inputType' => 'number',
                'label'     => 'Totaal PAR',
                'rules'     => ['required'],
                'columns'   => 3
            ],
            'stableford' => [
                'type'      => 'text',
                'inputType' => 'number',
                'label'     => 'Stableford',
                'rules'     => ['required'],
                'columns'   => 3
            ],
        ],
        'conditions' => [
            ['course_country_code', '!=', 'NL']
        ]
    ],
]
```

**Expected behavior:**

Loading the blabla values.

**Actual behavior:** 

Empty values.

**Comment by adamberecz** [comment]
This indeed should work and will be fixed in a couple of days. As a temporary solution you might also set `blabla` values manually on the frontend as a workaround.

**Comment by adamberecz** [comment]
Fixed in `1.2.11` @basvandertogt

**Comment by basvandertogt** [comment]
Last commit is from Nov 24, 2020. Issue is still stere after a composer and npm update.

**Comment by adamberecz** [comment]
This is where you find the release log for pro packages:
https://laraform.io/releases.

The last commit here is only for the _community_ version.

`1.2.11` is the latest version of npm package (pro). Can you confirm that you have `"@laraform/laraform": "1.2.11"` and still having this bug? I double checked on my end and it should be fine.

**Comment by basvandertogt** [comment]
Sorry i forgot to do a npm run after the update..
Issue is fixed. Thank you!
